stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

build:
  stage: build
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/app:latest .
    - docker push $CI_REGISTRY_IMAGE/app:latest
  only:
    - main

deploy:
  stage: deploy
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker stack deploy -c docker-compose.yml udemy
  only:
    - main
