version: "3.8"

services:
  app:
    image: registry.gitlab.com/raxmatjon/udemy/backend:latest
    ports:
      - "4000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MINIO_URL:  ${MINIO_URL}
      MINIO_USER: ${MINIO_USER}
      MINIO_SECRET_KEY: ${MINIO_PASS}
      MINIO_BUCKET_VIDEO: ${MINIO_BUCKET_VIDEO}
      JWT_AT_SECRET: ${JWT_AT_SECRET}
      JWT_RT_SECRET: ${JWT_RT_SECRET}
      SCRYPT_KEY: ${SCRYPT_KEY}
      SCRYPT_SALT: ${SCRYPT_SALT} 
      NODE_ENV: "production"
      MINIO_PORT: 9000

    depends_on:
      - postgres
      - minio
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_USER}
      MINIO_SECRET_KEY: ${MINIO_PASS}
    volumes:
      - miniodata:/data
    ports:
      - "9292:9000"
      - "9293:9001"
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  pgdata:
  miniodata:

networks:
  backend:
    driver: overlay
