stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""  # Needed for DinD — safe to keep even if not used

build:
  stage: build
  # tags:
  #   - docker  # <-- Match this to your runner’s tag
  script:
    - docker --version
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker build -t $CI_REGISTRY_IMAGE/app:latest .
    - docker push $CI_REGISTRY_IMAGE/app:latest
  only:
    - main

deploy:
  stage: deploy
  # tags:
  #   - docker
  script:
    - docker stack deploy -c docker-compose.yml udemy
  only:
    - main
