version: "3.8"

services:
  app:
    image: registry.gitlab.com/raxmatjon/udemy/app:latest
    ports:
      - "80:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/app
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    depends_on:
      - postgres
      - minio
    networks:
      - backend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - miniodata:/data
    ports:
      - "9292:9000"
      - "9293:9001"
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  pgdata:
  miniodata:

networks:
  backend:
    driver: overlay
